version: '3.8'

services:
  backend:
    container_name: fruits_api
    build:
      context: ./backend
    command: ["sh", "start.sh"]
    volumes:
      - ./backend:/api
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    env_file:
      - ".env"
    image: postgres:16.4-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES__DB_NAME} -U $${POSTGRES__USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES__USER}
      - POSTGRES_PASSWORD=${POSTGRES__PASSWORD}
      - POSTGRES_DB=${POSTGRES__DB_NAME}
  bot:
    container_name: fruits_bot
    build:
      context: ./bot
    command: ["python", "/bot/main.py"]
    volumes:
      - ./bot:/bot
    depends_on:
      - backend
