version: '3.8'

services:
  backend:
    container_name: fruits_api
    build:
      context: ./backend
    command: ["sh", "start.sh"]
    volumes:
      - ./backend:/api
    ports:
      - 8000:8000
    depends_on:
      - database
      - cache
  database:
    container_name: fruits_database
    env_file:
      - ".env"
    image: postgres:16.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES__USER}
      - POSTGRES_PASSWORD=${POSTGRES__PASSWORD}
      - POSTGRES_DB=${POSTGRES__DB_NAME}
  cache:
    container_name: fruits_cache
    image: redis:7.4.0
    ports:
      - "6379:6379"
  bot:
    container_name: fruits_bot
    build:
      context: ./bot
    command: ["python", "/bot/main.py"]
    volumes:
      - ./bot:/bot
    depends_on:
      - backend
